import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { writeFileSync, mkdirSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';

// -- test-file-parser --------------------------------------------------------

import {
  parseGeneratedTestFiles,
  extractTestGenComment,
} from '../src/utils/test-file-parser.js';

describe('parseGeneratedTestFiles', () => {
  it('extracts spec and handler files from AI response', () => {
    const response = `
Some preamble text.

#### \`tests/e2e/settings.spec.ts\`
\`\`\`typescript
import { test } from '../base-fixtures';
import { testSettingsLoad } from '../routes/settings/handler';

test.describe('Settings', () => {
  test('loads', async ({ page }) => {
    await testSettingsLoad(page);
  });
});
\`\`\`

#### \`tests/routes/settings/handler.ts\`
\`\`\`typescript
import { expect, type Page } from '@playwright/test';

export async function testSettingsLoad(page: Page): Promise<void> {
  await page.goto('/settings');
  await expect(page.locator('[data-pw="settings-heading"]')).toBeVisible();
}
\`\`\`

Some epilogue text.
`;

    const files = parseGeneratedTestFiles(response);
    expect(files).toHaveLength(2);
    expect(files[0].filePath).toBe('tests/e2e/settings.spec.ts');
    expect(files[0].content).toContain(
      "import { test } from '../base-fixtures'"
    );
    expect(files[1].filePath).toBe('tests/routes/settings/handler.ts');
    expect(files[1].content).toContain('testSettingsLoad');
  });

  it('returns empty array when no code blocks found', () => {
    const files = parseGeneratedTestFiles('No code here.');
    expect(files).toHaveLength(0);
  });

  it('handles json code blocks for mock files', () => {
    const response = `
#### \`src/mocks/routes/settings/data.json\`
\`\`\`json
{"key": "value"}
\`\`\`
`;
    const files = parseGeneratedTestFiles(response);
    expect(files).toHaveLength(1);
    expect(files[0].filePath).toBe('src/mocks/routes/settings/data.json');
  });
});

describe('extractTestGenComment', () => {
  it('extracts comment with footer', () => {
    const text =
      'Some text\n\n' +
      '## Lumos -- Test Generation (mock tests)\n\n' +
      '**Confidence: HIGH**\n\n' +
      '### Summary\nGenerated tests.\n\n' +
      '---\n*Generated by Lumos v2 | 3 source files analyzed*\n\n' +
      'More text';

    const comment = extractTestGenComment(text);
    expect(comment).not.toBeNull();
    expect(comment).toContain('## Lumos -- Test Generation');
    expect(comment).toContain('Generated by Lumos v2');
    expect(comment).not.toContain('More text');
  });

  it('returns null for non-test-gen text', () => {
    expect(extractTestGenComment('Just regular text.')).toBeNull();
  });
});

// -- jira-utils ---------------------------------------------------------------

import { extractTicketKey } from '../src/utils/jira-utils.js';

describe('extractTicketKey', () => {
  it('extracts ticket from branch name', () => {
    expect(extractTicketKey('BZ-1234-add-settings')).toBe('BZ-1234');
  });

  it('extracts ticket from prefixed branch', () => {
    expect(extractTicketKey('feature/BZ-567-my-feature')).toBe('BZ-567');
  });

  it('returns undefined when no ticket pattern', () => {
    expect(extractTicketKey('main')).toBeUndefined();
    expect(extractTicketKey('release')).toBeUndefined();
  });
});

// -- test-gen-prompt ----------------------------------------------------------

import {
  buildTestGenSystemPrompt,
  buildTestGenUserMessage,
} from '../src/prompts/test-gen-prompt.js';
import type { LumosConfig } from '../src/config.js';
import type { PrMetadata, ChangedFile } from '../src/parsers/types.js';

describe('buildTestGenSystemPrompt', () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = join(tmpdir(), `lumos-testgen-${Date.now()}`);
    mkdirSync(tmpDir, { recursive: true });
    mkdirSync(join(tmpDir, 'memory-bank'), { recursive: true });

    writeFileSync(
      join(tmpDir, 'memory-bank/test-generation-patterns.md'),
      '# Test Patterns\nUse data-pw selectors.\n'
    );
  });

  afterEach(() => {
    rmSync(tmpDir, { recursive: true, force: true });
  });

  function makeConfig(): LumosConfig {
    return {
      version: 1,
      ai: {
        provider: 'vertex',
        model: 'claude-sonnet-4-5@20250929',
        temperature: 0.1,
        maxTokens: 30000,
        timeout: '5m',
        maxTokenBudget: 1000000,
        maxCostPerRun: 5.0,
      },
      mcpServers: { jira: { enabled: false } },
      report: { jsonPath: 'test/json/result.json' },
      memoryBank: [],
      posting: { strategy: 'single' },
      observability: { langfuse: { enabled: false } },
      testGeneration: {
        patternsFile: 'memory-bank/test-generation-patterns.md',
      },
    };
  }

  it('includes all required sections', () => {
    const prompt = buildTestGenSystemPrompt(makeConfig(), tmpDir);

    expect(prompt).toContain('[ROLE]');
    expect(prompt).toContain('[AVAILABLE TOOLS]');
    expect(prompt).toContain('[WORKFLOW');
    expect(prompt).toContain('[TEST GENERATION GUIDELINES]');
    expect(prompt).toContain('[COMMENT FORMAT]');
    expect(prompt).toContain('[TEST PATTERNS]');
  });

  it('loads the patterns file content', () => {
    const prompt = buildTestGenSystemPrompt(makeConfig(), tmpDir);
    expect(prompt).toContain('Use data-pw selectors.');
  });

  it('does not include v1 analysis sections', () => {
    const prompt = buildTestGenSystemPrompt(makeConfig(), tmpDir);
    expect(prompt).not.toContain('[ANALYSIS GUIDELINES]');
    expect(prompt).not.toContain('SAFE TO MERGE');
    expect(prompt).not.toContain('NEEDS FIXES');
  });
});

describe('buildTestGenUserMessage', () => {
  it('formats PR context and file lists', () => {
    const pr: PrMetadata = {
      id: 4638,
      title: 'feat: add settings page',
      description: 'Adds a new settings page with user preferences.',
      sourceBranch: 'BZ-1234-add-settings',
      targetBranch: 'beta',
      changedFiles: [],
    };

    const sourceFiles: ChangedFile[] = [
      { path: 'src/routes/(app)/settings/+page.svelte', changeType: 'ADD' },
      {
        path: 'src/lib/components/SettingsForm/SettingsForm.svelte',
        changeType: 'ADD',
      },
    ];

    const nonSourceFiles: ChangedFile[] = [
      { path: 'package.json', changeType: 'MODIFY' },
    ];

    const message = buildTestGenUserMessage(pr, sourceFiles, nonSourceFiles);

    expect(message).toContain('PR #4638');
    expect(message).toContain('feat: add settings page');
    expect(message).toContain('src/routes/(app)/settings/+page.svelte');
    expect(message).toContain(
      'src/lib/components/SettingsForm/SettingsForm.svelte'
    );
    expect(message).toContain('package.json');
    expect(message).toContain('Non-Source Files');
    expect(message).toContain('Follow the [WORKFLOW]');
  });

  it('includes existing test hints when provided', () => {
    const pr: PrMetadata = {
      id: 4638,
      title: 'feat: update settings page',
      description: '',
      sourceBranch: 'BZ-1234-update-settings',
      targetBranch: 'beta',
      changedFiles: [],
    };

    const sourceFiles: ChangedFile[] = [
      { path: 'src/routes/(app)/settings/+page.svelte', changeType: 'MODIFY' },
    ];

    const hints = ['tests/routes/settings/ (check for existing handlers)'];

    const message = buildTestGenUserMessage(pr, sourceFiles, [], hints);

    expect(message).toContain('Existing Tests for Changed Areas');
    expect(message).toContain('tests/routes/settings/');
  });

  it('omits existing test hints section when no hints', () => {
    const pr: PrMetadata = {
      id: 4638,
      title: 'feat: new feature',
      description: '',
      sourceBranch: 'BZ-9999-new-feature',
      targetBranch: 'beta',
      changedFiles: [],
    };

    const message = buildTestGenUserMessage(
      pr,
      [
        {
          path: 'src/routes/(app)/new-feature/+page.svelte',
          changeType: 'ADD',
        },
      ],
      []
    );

    expect(message).not.toContain('Existing Tests');
  });
});

// -- orchestrator: isTestableSourceFile ----------------------------------------

describe('isTestableSourceFile (via orchestrator internals)', () => {
  // We test the logic directly since the method is private.
  // Replicate the same regex logic here.
  function isTestable(filePath: string): boolean {
    const testable = [
      /^src\/routes\//,
      /^src\/lib\/components\//,
      /^src\/lib\/services\//,
      /^src\/lib\/stores\//,
    ];
    const excluded = [
      /^tests\//,
      /\.spec\.(ts|js)$/,
      /\.test\.(ts|js)$/,
      /\.(css|scss|json|md|svg|png|jpg|gif)$/,
      /node_modules/,
    ];
    return (
      testable.some((p) => p.test(filePath)) &&
      !excluded.some((p) => p.test(filePath))
    );
  }

  it('accepts route files', () => {
    expect(isTestable('src/routes/(app)/settings/+page.svelte')).toBe(true);
    expect(isTestable('src/routes/(app)/settings/+page.ts')).toBe(true);
  });

  it('accepts component files', () => {
    expect(isTestable('src/lib/components/Button/Button.svelte')).toBe(true);
  });

  it('accepts service files', () => {
    expect(isTestable('src/lib/services/client/settings.ts')).toBe(true);
  });

  it('accepts store files', () => {
    expect(isTestable('src/lib/stores/session.store.ts')).toBe(true);
  });

  it('rejects test files', () => {
    expect(isTestable('tests/e2e/settings.spec.ts')).toBe(false);
    expect(isTestable('tests/routes/settings/handler.ts')).toBe(false);
  });

  it('rejects CSS/JSON/MD files', () => {
    expect(isTestable('src/routes/(app)/settings/style.css')).toBe(false);
    expect(isTestable('src/lib/components/Button/config.json')).toBe(false);
  });

  it('rejects non-source paths', () => {
    expect(isTestable('package.json')).toBe(false);
    expect(isTestable('README.md')).toBe(false);
    expect(isTestable('scripts/run-lumos.js')).toBe(false);
  });
});
