import type { GeneratedTestFile } from '../parsers/types.js';

// ---------------------------------------------------------------------------
// Parse generated test files from AI response
//
// The AI outputs test code in a structured markdown format:
//   #### `tests/e2e/feature.spec.ts`
//   ```typescript
//   ...code...
//   ```
// ---------------------------------------------------------------------------

/**
 * Extract generated test files from the AI's response text.
 *
 * Looks for patterns like:
 *   #### `<file-path>`
 *   ```typescript
 *   <code>
 *   ```
 */
export function parseGeneratedTestFiles(
  responseText: string
): GeneratedTestFile[] {
  const files: GeneratedTestFile[] = [];

  // Match: #### `filepath`\n```lang\n...code...\n```
  const pattern =
    /####\s+`([^`]+)`\s*\n```(?:typescript|ts|javascript|js|json)?\s*\n([\s\S]*?)```/g;

  let match: RegExpExecArray | null;
  while ((match = pattern.exec(responseText)) !== null) {
    const filePath = match[1].trim();
    const content = match[2].trimEnd();

    if (filePath && content) {
      files.push({ filePath, content });
    }
  }

  return files;
}

/**
 * Extract the Lumos test generation comment from the AI response.
 *
 * Looks for content starting with "## Lumos -- Test Generation" and ending
 * at the footer "*Generated by Lumos*" or end of text.
 */
export function extractTestGenComment(responseText: string): string | null {
  const startIdx = responseText.indexOf('## Lumos -- Test Generation');
  if (startIdx === -1) return null;

  const footerPattern = /\*Generated by Lumos[^*]*\*/;
  const footerMatch = footerPattern.exec(responseText.slice(startIdx));

  let comment: string;
  if (footerMatch) {
    comment = responseText.slice(
      startIdx,
      startIdx + footerMatch.index + footerMatch[0].length
    );
  } else {
    comment = responseText.slice(startIdx);
  }

  if (comment.length < 100) return null;

  return comment.trim();
}
